name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Crear zip para el frontend
      - name: Comprimir Frontend
        run: |
          cd root/frontend
          zip -r ../../frontend.zip .

      # Crear zip para el backend
      - name: Comprimir Backend
        run: |
          cd root/backend
          zip -r ../../backend.zip .

      # Subir artefactos para despliegue
      - name: Subir Artefactos
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            frontend.zip
            backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: "formulario-unidad5" # Reemplaza con el nombre de tu aplicación en Azure
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./backend.zip

      - name: Deploy Frontend
        uses: azure/webapps-deploy@v2
        with:
          app-name: "formulario-unidad5" # Reemplaza con el nombre de tu aplicación en Azure
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./frontend.zip