name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Crear zip para el frontend
      - name: Zip static frontend
        run: |
          cd frontend
          zip -r ../frontend.zip .

      # Crear zip para el backend
      - name: Zip backend
        run: |
          cd backend
          zip -r ../backend.zip .

      # Subir artefactos
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: |
            backend.zip
            frontend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Deploy Backend to Azure
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_PUBLISH_URL: ${{ secrets.AZURE_PUBLISH_URL }}
        run: |
          echo "Deploying backend to Azure..."
          curl -X POST -u $AZURE_USER:$AZURE_PASSWORD \
          --data-binary @backend.zip https://$AZURE_PUBLISH_URL/api/zipdeploy

      - name: Deploy Frontend to Azure
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_PUBLISH_URL: ${{ secrets.AZURE_PUBLISH_URL }}
        run: |
          echo "Deploying frontend to Azure..."
          curl -X POST -u $AZURE_USER:$AZURE_PASSWORD \
          --data-binary @frontend.zip https://$AZURE_PUBLISH_URL/api/zipdeploy