name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar dependencias
        working-directory: ./root/backend
        run: npm install

      - name: Comprimir todo en un ZIP
        run: |
          cd root/backend
          zip -r ../../deploy.zip .

      - name: Subir a Azure
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          AZURE_PUBLISH_URL: ${{ secrets.AZURE_BACKEND_PUBLISH_URL }}
        run: |
          echo "Deploying application to Azure..."
          curl -X POST -u $AZURE_USER:$AZURE_PASSWORD \
          --data-binary @deploy.zip https://$AZURE_PUBLISH_URL/api/zipdeploy