name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Create release zip
        run: |
          cd backend
          zip -r release.zip .

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: backend/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v3
        with:
          name: release

      - name: Deploy to Azure
        run: |
          echo "Deploying to Azure..."
          # Aquí puedes incluir comandos para el despliegue en Azure.