name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Instalar dependencias
        working-directory: ./root/backend
        run: npm install

      - name: Comprimir todo en un ZIP
        run: |
          cd root/backend
          zip -r ../../deploy.zip .

      - name: Deploy to Azure
        env:
          AZURE_USER: '$formulario-unidad5'
          AZURE_PASSWORD: 'rNfA8ZR4zF6h7rkxeSLk5uGi9P5RiR3dY9y5a4HRvz4mwJLzZ71d6dugovbc'
          AZURE_PUBLISH_URL: formulario-unidad5-fhfuerbqbpgth7bn.scm.eastus2-01.azurewebsites.net
        run: |
          echo "Deploying application to Azure..."
          curl -X POST -u $AZURE_USER:$AZURE_PASSWORD \
          --data-binary @deploy.zip https://$AZURE_PUBLISH_URL/api/zipdeploy